name: Main CI Tests

on:
  workflow_call:

jobs:
  karma-tests:
    uses: ./.github/workflows/karma-tests.yml
  cypress-e2e-tests:
      needs: [karma-tests]
      uses: ./.github/workflows/cypress-e2e-tests.yml
