name: Main CI Tests

on:
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  karma-tests:
    uses: ./.github/workflows/karma-tests.yml
  cypress-e2e-tests:
      uses: ./.github/workflows/cypress-e2e-tests.yml
